site_name: ULA
site_description: 'Documentación Lenguaje ULA'
site_url: 'https://juliolugo96.github.io/ula-lang/'
site_author: 'Julio Lugo'

repo_name: 'juliolugo96/ula-lang'
repo_url: 'https://github.com/juliolugo96/ula-lang'

copyright: 'Copyright &copy; 2020 Julio Lugo'

nav:
  - Lesma: index.md
  - Examples: examples.md
  - Features:
    - Syntax: features/syntax.md
    - Keywords: features/keywords.md
    - Flow Control: features/flow_control.md
    - Structs: features/structs.md
    - Classes: features/classes.md
    - Enums: features/enums.md
    - Types: features/types.md
    - Operators: features/operators.md
  - TODO: TODO.md
  - License: license.md

extra_css:
    - css/extra.css

theme: 
  name: 'material'
  palette: 
    primary: 'blue'
    accent: 'blue'
  font:
    text: 'Noto Sans'
    code: 'Roboto Mono'
  logo:
    icon: 'book'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: False
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite